### ISSUE TITLE
Track events do not support url as a standard property

### ISSUE THREAD

**Issue by guillaumecabane** [segment-integrations/integration-google-analytics#2]
There is no support for the url property in the current mapper, hence all track events are sent to GA without a url.
As a consequence, filters applied on views to separate subdomain trafic (blog for example) will display ALL track events, skewing the view's data completely

**Comment by sperand-io** [comment]
@guillaumecabane just an FYI that we're discussing options here internally w/r/t to our fundamental event spec, and how we could accommodate this more holistically

**Comment by sperand-io** [comment]
https://github.com/segment-integrations/integration-google-analytics/blob/master/lib/universal/mapper.js#L70
