### ISSUE TITLE
Queue Time Parameter

### ISSUE THREAD

**Issue by sperand-io** [segment-integrations/integration-google-analytics#3]
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#qt

Would it make sense on the server side to compute `receivedAt` - `timestamp` and pass it along as time spent in the server/device queue? (as they batch events)?

@DirtyAnalytics @amillet89 @ianstormtaylor

**Comment by f2prateek** [comment]
Seems like it's more the time spent in the queue before reaching the servers, i.e. from our client libraries.

**Comment by peetersn** [comment]
We are interested in this feature. cc @jayant-simpragma @varunnaik

**Comment by f2prateek** [comment]
@sperand-io ah never mind, I see how you're computing it. Makes sense to me.

**Comment by hankim813** [comment]
added to JIRA for internal tracking https://segment.atlassian.net/browse/INT-173
