### ISSUE TITLE
Send custom dimensions and metrics via `.track()`

### ISSUE THREAD

**Issue by lambtron** [segment-integrations/integration-google-analytics#4]
Google's measurement protocol:
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cd_

Seems like we can just add it in here:
https://github.com/segmentio/integration-google-analytics/blob/master/lib/mapper.js#L117

Similar to how we do it here:
https://github.com/segmentio/analytics.js-integrations/blob/master/lib/google-analytics/index.js#L503

Thoughts?

/cc @amillet89 @sperand-io

**Comment by mpestritto** [comment]
Is this already mapped through the metrics method?
https://github.com/segmentio/integration-google-analytics/blob/master/lib/mapper.js#L128
https://github.com/segmentio/integration-google-analytics/blob/master/lib/mapper.js#L172

If it is, I can't figure out what the payload on the server side event needs to be to pass the data through to GA.

Thanks.

**Comment by sperand-io** [comment]
https://github.com/segment-integrations/integration-google-analytics/blob/master/lib/universal/mapper.js#L589-L592

@mpestritto if you're still having trouble getting those mapped correctly, please ping friends@segment.com and they'll help you get it sorted!
