### ISSUE TITLE
Add server side ecommerce events

### ISSUE THREAD

**Issue by lambtron** [segment-integrations/integration-google-analytics#5]
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#enhanced-ecomm

**Comment by kzap** [comment]
+1 :) ill submit a PR for Refund Order since its rather simple ....

**Comment by kzap** [comment]
not sure about converting the entire Completed Order to Enhanced Ecommerce, you gain a few extra fields and per product coupons

what other events would be important server side?

**Comment by sperand-io** [comment]
https://github.com/segment-integrations/integration-google-analytics/pull/31 :boom:
